---
- name: Create DNS server and domain
  na_ontap_dns:
    state: "{{ item.state }}"
    vserver: "{{ item.vserver }}"
    domains: "{{ item.domains }}"
    nameservers: "{{ item.nameservers }}"
    skip_validation: true
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
  with_items: "{{ dns }}"

