---
- name: Create NTP server
  na_ontap_ntp:
    state: present
    server_name: "{{ item.server_name }}"
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
  with_items: "{{ ntp }}"

