---
- name: Check SNMP state
  na_ontap_command:
    command: ["options", "-option-name", "snmp.enable"]
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
  register: result_snmp_state
  changed_when: false

- name: Change SNMP state
  na_ontap_command:
    command: ["options", "-option-name", "snmp.enable", "-option-value", "{{ snmp.state }}"]
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
  when: result_snmp_state.msg | regex_replace('^.*\\n\\s+snmp\\.enable\\s+(\\S+).*$', '\\1') != snmp.state

- name: Add SNMP community
  na_ontap_snmp:
    state: present
    access_control: ro
    community_name: "{{ snmp.community_name }}"
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
  when: snmp.state == "on"

- name: Check SNMP contact
  na_ontap_command:
    command: ["system", "snmp", "contact"]
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
  register: result_contact
  changed_when: false
  when: snmp.state == "on"

- name: Set SNMP contact
  na_ontap_command:
    command: ["system", "snmp", "contact", "-contact", "{{ snmp.contact }}"]
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
  when:
    - snmp.state == "on"
    - not result_contact.msg | regex_search((snmp.contact))

- name: Check SNMP location
  na_ontap_command:
    command: ["system", "snmp", "location"]
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
  register: result_location
  changed_when: false
  when: snmp.state == "on"

- name: Set SNMP location
  na_ontap_command:
    command: ["system", "snmp", "location", "-location", "{{ snmp.location }}"]
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
  when:
    - snmp.state == "on"
    - not result_location.msg | regex_search((snmp.location))

- name: Check SNMP trap state
  na_ontap_command:
    command: ["system", "snmp", "init"]
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
  register: result_snmp_trap_state
  changed_when: false
  when: snmp.state == "on"

- name: Change SNMP trap state
  na_ontap_command:
    command: ["system", "snmp", "init", "{{ snmp.init }}"]
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
  when: 
    - snmp.state == "on"
    - result_snmp_trap_state.msg | regex_replace('^.*<cli-output>\\s+(\\d)\\n\\n.*$', '\\1') != snmp.init

- name: Import set_snmp_trap_host.yml
  include_tasks: set_snmp_trap_host.yml
  with_items: "{{ snmp.host }}"
  loop_control:
    loop_var: traphost
  when: 
    - snmp.state == "on"
    - snmp.init == "1"

