- name: Check SNMP trap host
  na_ontap_command:
    command: ["system", "snmp", "traphost", "show"]
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
  changed_when: false
  register: result

- name: Add SNMP trap host
  na_ontap_command:
    command: ["system", "snmp", "traphost", "add", "-peer-address", "{{ traphost }}"]
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
  when: not result.msg | regex_search((traphost))

