---
- name: Delete broadcast domain port
  na_ontap_broadcast_domain_ports:
    state: absent
    broadcast_domain: "{{ broadcast_domain_port_for_delete.broadcast_domain }}"
    ports: "{{ broadcast_domain_port_for_delete.ports }}"
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"

