---
- name: Create volume
  na_ontap_volume:
    state: present
    name: "{{ item.name }}"
    aggregate_name: "{{ item.aggregate_name }}"
    vserver: "{{ item.vserver }}"
    size: "{{ item.size }}"
    size_unit: "{{ item.size_unit }}"
    type: "{{ item.type }}"
    language: "{{ item.language }}"
    volume_security_style: "{{ item.security_style }}"
    percent_snapshot_space: "{{ item.percent_snapshot_space }}"
    junction_path: "{{ item.junction_path | default(omit) }}"
    policy: "{{ item.policy }}"
    snapshot_policy: "{{ item.snapshot_policy | default(omit) }}"
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
  with_items: "{{ volume }}"

