---
hostname: cluster1
username: admin
password: Netapp1!
node:
  - name: cluster1-002
    from_name: cluster1-02
ntp:
  - server_name: ntp.nict.jp
timezone: Asia/Tokyo
snmp:
  state: "on"
  community_name: test_community
  contact: test
  location: test
  init: "1"
  host:
    - 192.168.0.102
    - 192.168.0.103
autosupport:
  state: present
  node_name: cluster1-01
  mail_hosts: example.com
  from_address: netapp@example.com
  to_addresses: test1@example.com,test2@example.com
  partner_addresses: pertner1@example.com,pertner2@example.com
  support: true
  transport: https
  proxy_url: example.com
job:
  - name: test_job
    minutes: 15
    #hours: 6
    #days_of_month: 1
    #days_of_week: 5
    #months: 2
service_processor:
  - node: cluster1-01
    address_type: ipv4
    dhcp: none
    ip_address: 192.168.0.132
    netmask: 255.255.255.0
    gateway_ip_address: 192.168.0.1
broadcast_domain_port_for_delete:
  broadcast_domain: Default
  ports: ["cluster1-01:e0d", "cluster1-01:e0e", "cluster1-01:e0f", "cluster1-01:e0g", "cluster1-002:e0d", "cluster1-002:e0e", "cluster1-002:e0f", "cluster1-002:e0g"]
ifgrp:
  - name: a0a
    node: cluster1-01
    ports: ["e0e", "e0f"]
    mode: singlemode
    distribution_function: port
vlan:
  - node: cluster1-01
    vlanid: 100
    parent_interface: a0a
broadcast_domain:
  - name: Data
    mtu: 1500
    #ipspace: Data  
broadcast_domain_port_for_create:
  - broadcast_domain: Default
    ports: ["cluster1-01:a0a-100"]
network_port:
  - node: cluster1-01
    ports: ["e0c", "e0d"]
    autonegotiate_admin: "true"
    speed_admin: auto
    flowcontrol_admin: none
    mtu: 1500
aggregate:
  - name: aggr0_test
    nodes: cluster1-002
    disk_count: 5
    raid_type: raid_dp
volume:
  - name: vol2
    aggregate_name: aggr0_test
    vserver: svm_nfs
    size: 5
    size_unit: gb
    type: RW
    language: ja_v1
    security_style: unix
    percent_snapshot_space: 0
    #junction_path: /test
    policy: default
    snapshot_policy: default
svm:
  - name: svm_nfs
    root_volume: svm_nfs_root
    root_volume_aggregate: aggr0_test
    root_volume_security_style: unix
    language: ja_v1
    aggr_list: aggr0_test
    allowed_protocols: nfs,cifs
dns:
  - state: present
    vserver: svm_nfs
    domains: demo.netapp.com
    nameservers: 192.168.0.253
failover_group:
  - name: test
    vserver: cluster1
    targets:
      - cluster1-01:a0a-100
      - cluster1-01:e0c
      - cluster1-002:e0c
lif:
  - name: svm_nfs_lif
    vserver: svm_nfs
    address: 192.168.0.122
    netmask: 255.255.255.0
    home_node: cluster1-01
    home_port: a0a-100
    role: data
    protocols: nfs
    failover_policy: system-defined
    #firewall_policy: mgmt
    is_auto_revert: false
export_policy:
  - name: default
    vserver: svm_nfs
    rule_index: 1
    client_match: 0.0.0.0/0
    protocol: nfs3
    ro_rule: any
    rw_rule: any
    super_user_security: any
snapshot_policy:
  - name: test_snapshot_policy
    vserver: svm_nfs
    schedule: ["hourly", "daily"]
    count: [6, 2]
nfs:
  - vserver: svm_nfs
    nfsv3: enabled
    nfsv4: disabled
    nfsv41: disabled
    tcp: enabled
    udp: disabled
    #nfsv4_id_domain: demo.netapp.com
cifs:
  - name: test_cifs
    vserver: svm_nfs
    #domain: demo.netapp.com
    #admin_user_name: Administrator
    #admin_password: Netapp1!
    workgroup: test
cifs_share:
  - name: test_share
    vserver: svm_nfs
    path: /test
    properties: oplocks,browsable,changenotify

