---
hostname: cluster1
username: admin
password: XXXXX
timezone: Asia/Tokyo
network_port:
  node: cluster1-01
  ports: e0a,e0b
  speed_admin: auto
  flowcontrol_admin: none
  mtu: 9000
broadcast_domain:
  name: Default
  mtu: 1500
  ipspace: Default  
broadcast_domain_port_for_delete:
  broadcast_domain: Default
  ports: ["cluster1-01:e0e", "cluster1-01:e0f"]
broadcast_domain_port_for_create:
  broadcast_domain: Default
  ports: ["cluster1-01:a0a"]
ifgrp:
  name: a0a
  node: cluster1-01
  ports: [e0e, e0f]
  mode: singlemode
  distribution_function: port
vlan:
  node: cluster1-01
  vlanid: 100
  parent_interface: a0a
service_processor:
  node: cluster1-01
  address_type: ipv4
  dhcp: none
  ip_address: 192.168.0.135
  netmask: 255.255.255.0
  gateway_ip_addres: 192.168.0.1
aggregate:
  name: aggr0_test
  nodes: cluster1-02
  disk_count: 5
  raid_type: raid_dp
svm:
  name: svm_nfs
  root_volume: svm_nfs_root
  root_volume_aggregate: aggr0_test
  root_volume_security_style: unix
  language: ja_v1
  aggr_list: aggr0_test
  allowed_protocols: nfs,cifs
volume:
  name: vol1
  aggregate_name: aggr0_test
  vserver: svm_nfs
  size: 5
  size_unit: gb
  type: RW
  language: ja_v1
  security_style: unix
  percent_snapshot_space: 0
  junction_path: /test
  policy: default
  snapshot_policy: default
lif:
  name: svm_nfs_lif
  vserver: svm_nfs
  address: 192.168.0.120
  netmask: 255.255.255.0
  home_node: cluster1-02
  home_port: e0d
  role: data
  protocols: nfs
  failover_policy: system-defined
  #firewall_policy: mgmt
  is_auto_revert: false
export_policy:
  name: default
  vserver: svm_nfs
  rule_index: 1
  client_match: 0.0.0.0/0
  protocol: nfs3
  ro_rule: any
  rw_rule: any
  super_user_security: any
snapshot_policy:
  name: test_snapshot_policy
  vserver: svm_nfs
  schedule: ["hourly", "daily"]
  count: [6, 2]
nfs:
  vserver: svm_nfs
  nfsv3: enabled
  nfsv4: disabled
  nfsv41: disabled
  tcp: enabled
  udp: disabled
  #nfsv4_id_domain: example.com
cifs:
  name: test_cifs
  vserver: svm_nfs
  domain: example.com
  admin_user_name: Administrator
  admin_password: XXXXX
  #workgroup: test
cifs_share:
  name: test_share
  vserver: svm_nfs
  path: /test
  properties: oplocks,browsable,changenotify
ntp:
  state: absent
  version: auto
  server_name: ntp.nict.jp
dns:
  state: present
  vserver: cluster1
  domains: example.com
  nameservers: 192.168.0.253
autosupport:
  state: present
  node_name: cluster1-01
  mail_hosts: example.com
  from_address: netapp@example.com
  to_addresses: test1@example.com,test2@example.com
  partner_addresses: pertner1@example.com,pertner2@example.com
  support: true
  transport: https
  proxy_url: example.com
snmp:
  state: "on"
  community_name: test_community

