---
- name: Modify service processor
  na_ontap_service_processor_network:
    state: present
    is_enabled: true
    node: "{{ item.node }}"
    address_type: "{{ item.address_type }}"
    dhcp: "{{ item.dhcp }}"
    ip_address: "{{ item.ip_address | default(omit) }}"
    netmask: "{{ item.netmask | default(omit) }}"
    gateway_ip_address: "{{ item.gateway_ip_address | default(omit) }}"
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
  with_items: "{{ service_processor }}"

